fix(base_http): allow more than 128 HTTP response headers
[aiohttp 3.13.4](https://github.com/aio-libs/aiohttp/pull/11955/changes) changed the
allowed response header numbers from 32768 to 128.

Leading to:
```py-bt
Traceback (most recent call last):
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client_proto.py", line 317, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 596, in aiohttp._http_parser.HttpParser.feed_data
  File "aiohttp/_http_parser.pyx", line 758, in aiohttp._http_parser.cb_on_header_field
  File "aiohttp/_http_parser.pyx", line 434, in aiohttp._http_parser.HttpParser._on_header_field
  File "aiohttp/_http_parser.pyx", line 421, in aiohttp._http_parser.HttpParser._process_header
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Too many headers received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 539, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/streams.py", line 707, in read
    await self._waiter
aiohttp.http_exceptions.HttpProcessingError: 400, message:
  Too many headers received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/python-udm-rest-api-client/tests/test_base_http.py", line 1209, in test_request_language_header
    await meth(language=lang_request)
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/python-udm-rest-api-client/udm_rest_client/udm.py", line 221, in modules_list
    body = await self.session.get_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/python-udm-rest-api-client/udm_rest_client/base_http.py", line 305, in get_json
    response, content = await self.make_request("GET", url, language, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/python-udm-rest-api-client/udm_rest_client/base_http.py", line 325, in make_request
    async with self.session.get(url, **request_kwargs) as response:
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client.py", line 1521, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client.py", line 788, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client.py", line 766, in _connect_and_send_request
    await resp.start(conn)
  File "/usr/share/ucs-test/73_udm-rest/ucs-test-udm-rest-api/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 541, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Too many headers received', url='https://master090.autotest090.test/univention/udm/navigation/'
```